urls.py
# coding: utf-8
from django.conf.urls import url

from . import views

app_name = 'blogs'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^popular/$', views.PopularBlog.as_view(), name='popular'),
    url(r'^(?P<pk>[0-9]+)/subscribe/$',
        views.add_subscription, name='subscribe'),
    url(r'^(?P<pk>[0-9]+)/del_subscribe/$',
        views.delete_subscription, name='del_subscribe'),
    url(r'^post/(?P<pk>[0-9]+)/$',
        views.PostDetailView.as_view(),
        name='post-detail'),
    url(r'^post/(?P<pk>[0-9]+)/update/$',
        views.PostUpdate.as_view(),
        name='post-update'),
    url(r'post/add/$', views.PostAdd.as_view(), name='post-add'),
    url(r'add/$', views.BlogAdd.as_view(), name='blog-add'),
    url(r'(?P<pk>[0-9]+)/update/$',
        views.BlogUpdate.as_view(),
        name='blog-update'),
]

templates/blogs/blog_add.html
<!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}" />
<body>
<div>
<form action="{% url 'blogs:blog-add' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />

</form>
</div>
</body>

templates/blogs/blog_update.html
<!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}" />
<body>
<div>
<form action="{% url 'blogs:blog-update' blog.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить" />

</form>
</div>
</body>

templates/blogs/detail.html
<!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}" />
<h1>{{ blog.title }}</h1>
<h2>{{ blog.user.username }}</h2>

<ul>
{% for post in list_post %}
	
	<li><strong>{{ post.title }} </strong> Создан: {{ post.created }} 
	<p>{{ post.body }}</p>
	<a href="{% url 'blogs:post-detail' post.id %}">
		{% if post.on_read %} 
			Прочитано
		{% else %}
			Новое
		{% endif %}
	</a></li>


{% endfor %}
</ul>

{% if user.is_authenticated %}
	{% if subscribed %}
		<form action="{% url 'blogs:del_subscribe' blog.id %}" method="POST">
		{% csrf_token %}
		<input type="submit" value="Отписаться" />
		</form>
	{% else %}
		<form action="{% url 'blogs:subscribe' blog.id %}" method="POST">
		{% csrf_token %}
		<input type="submit" value="Подписаться" />
		</form>
	{% endif %}
{% endif %}

<br>
<br>
<a href="{% url 'blogs:index' %}">На главную</a>

<div class="pagination" align="center">
	<span class="current">
		Страница {{ list_post.number }} из {{ list_post.paginator.num_pages }}
	</span>
	<span class="step-links">
		{% if list_post.has_previous %}
			<a href="?page={{ list_post.previous_page_number }}">Предыдущая</a>
		{% endif %}
		{% if list_post.has_next %}
			<a href="?page={{ list_post.next_page_number }}">Следующая</a>
		{% endif %}
	</span>
</div>

templates/blogs/index.html
<!DOCTYPE html>
{% csrf_token %}
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}" />
{% if user.is_authenticated %}
	<div class="my_blog">
	{% if my_blog %}
		<ul><b>Мой блог </b> <a href="{% url 'blogs:detail' my_blog.id %}">Подробнее</a>
		{% if my_post %}
			{% for post in my_post %}
				<li><p>{{ post.title }} </p>
				<p>{{post.body|truncatechars:250}} </p></li>
			{% endfor %}
		{% endif %}
		</ul>
	{% endif %}
	</div>
	<div class="no_blog">
	{% if no_blog %}
		{{ no_blog }} <a href="{% url 'blogs:blog-add' %}">Начать</a>
	{% endif %}
	</div>
	<div class="subscribe">
	{% if list %}
	<b>Подписки</b><br>
		{% for li in list %}
			<p><b>{{ li.blog }} </b> {{ li.title }}</p>
			<p>{{li.body|truncatechars:180}} 
			<a href="{% url 'blogs:post-detail' li.id %}">
			{% if li.on_read %} 
				Прочитано
			{% else %}
				Новое
			{% endif %}
			</a></p>
		{% endfor %}
	{% else %}
		<p><b>Вы не подписаны на блоги</b></p>
	{% endif %}
	</div>
{% else %}
	<p> Войдите для просмотра подписок на блоги </p>
{% endif %}

<div class="popular">
<b>Популярные блоги</b>
{% if blog_list %}
	<ul>
	{% for i in blog_list %}
		<li>  {{ i.title }} {{i.user}} <a href="{% url 'blogs:detail' i.id %}">Подробнее</a></li>
	{% endfor %}
	</ul>
	{% endif %}
	<a href="{% url 'blogs:popular' %}">Смотреть все</a>
</div>

<div class="pagination" align="center">
	<span class="current">
		Страница {{ list.number }} из {{ list.paginator.num_pages }}
	</span>
	<span class="step-links">
		{% if list.has_previous %}
			<a href="?page={{ list.previous_page_number }}">Предыдущая</a>
		{% endif %}
		{% if list.has_next %}
			<a href="?page={{ list.next_page_number }}">Следующая</a>
		{% endif %}
	</span>
</div>

templates/blogs/my_blog.html
<!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}" />
{% csrf_token %}
<h1>{{ blog.title }}</h1>
<h2>{{ blog.user.username }}</h2>

<ul>
{% for post in list_post %}
	<li><strong>{{ post.title }} </strong> Создан: {{ post.created }} 
	<p>{{ post.body }}</p><a href="{% url 'blogs:post-detail' post.id %}">Подробнее</a></li>

{% endfor %}
</ul>

<p><a href="{% url 'blogs:post-add' %}">Добавить пост</a> </p>
<br>
<a href="{% url 'blogs:index' %}">На главную</a>
<div class="pagination" align="center">
	<span class="current">
		Страница {{ list_post.number }} из {{ list_post.paginator.num_pages }}
	</span>
	<span class="step-links">
		{% if list_post.has_previous %}
			<a href="?page={{ list_post.previous_page_number }}">Предыдущая</a>
		{% endif %}
		{% if list_post.has_next %}
			<a href="?page={{ list_post.next_page_number }}">Следующая</a>
		{% endif %}
	</span>
</div>

templates/blogs/popular.html
<!DOCTYPE html>
{% csrf_token %}
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}" />

<div class="popular">
{% if list %}
<b>Популярные блоги</b
	<ul>
	{% for i in list %}
		<li>  {{ i.title }} {{i.user}} <p> <a href="{% url 'blogs:detail' i.id %}">Подробнее</a></p></li>
	{% endfor %}
{% endif %}
	</ul>
</div>

<div class="pagination" align="center">
	<span class="current">
		Страница {{ list.number }} из {{ list.paginator.num_pages }}
	</span>
	<span class="step-links">
		{% if list.has_previous %}
			<a href="?page={{ list.previous_page_number }}">Предыдущая</a>
		{% endif %}
		{% if list.has_next %}
			<a href="?page={{ list.next_page_number }}">Следующая</a>
		{% endif %}
	</span>
</div>

templates/blogs/post_add.html
<!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}" />
{% csrf_token %}
<body>
<div>
<form action="{% url 'blogs:post-add' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />

</form>
</div>
<br>
<a href="{% url 'blogs:index' %}">На главную</a>
<footer>

</footer>
</body>

templates/blogs/post_detail.html
<!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}" />
{% csrf_token %}
<h1>{{ post.title }}</h1>
<h2>{{ post.body }}</h2>

{% if updated %}
	<p><a href="{% url 'blogs:post-update' post.id %}">Редактировать пост</a></p>
{% endif %}
<p><a href="{% url 'blogs:detail' post.blog.id %}">Перейти к блогу</a> </p>
<p><a href="{% url 'blogs:index' %}">На главную</a> </p>
<ul>
{% for a in post.comments.all %}
    <li>{{ a.user }}</li>
	<p>{{ a.body }}</p>
{% endfor %}

</ul>
<div>
<form action=" " method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить комментарий" />
</form>
</div>

templates/blogs/post_update.html
<!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}" />
<body>
<div>
<form action="{% url 'blogs:post-update' post.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить" />

</form>
</div>
</body>